### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rajatRS**
I have updated the README.md file. Included the following informations :-
1. Getting Started with koala
2. Features
3. Installation Guide
4. Add Project
5. How to run koala?

### CODE REVIEW

**Comment by rajatRS** [comment]
Please let me know your views, so that I could make any required changes.

**Review by skyclo — CHANGES_REQUESTED** [review]
This README does not pertain to the focus of Ideoxan nor it's editor. See https://github.com/ideoxan/ideoxan#readme if you are confused as to what this project is about. Please make the proper changes to reflect this.

**Comment by rajatRS** [comment]
I went through the Ideoxan README.md file. Is it that I have to make a README file with the same content as given there.

**Comment by skyclo** [comment]
> I went through the Ideoxan README.md file. Is it that I have to make a README file with the same content as given there.

It is not necessarily the fact that it doesn't follow the format from the main repo, its the fact that the proposed README does not pertain to the editor. 

I suggested using the README from the main repo and changing it because it would kept uniformity (which isn't really a point of concern with this repo). It also would have made it very easy to create a PR.

The proposed README mentions features that aren't included in the editor. It mentions the webpack bundler even though the editor does not use this.

I suggest you clone the main repo and run it to check out the editor if you wish to describe the features in the README. Otherwise, I still need for you to modify the README to fit the purpose and function of the editor.

**Comment by skyclo** [comment]
Please let me know if you plan to work on this otherwise this will be marked as invalid, closed, and assigned to someone else.

**Comment by rajatRS** [comment]
Sorry, I wasn't able to make it.
You may assign it to anyone else.

**Pull request closed without merging**
